CREATE TABLE dbo.CHRISTIAN_SHIELDS_MEMBERS (
    id INT IDENTITY(1,1) PRIMARY KEY,
    email NVARCHAR(255) NOT NULL UNIQUE,
    is_email_subscribed BIT DEFAULT 1,
    created_at DATETIME DEFAULT GETDATE()
);
